#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;

const int MAXN = 500;
int min_p[MAXN];
int sum_d[MAXN];
#define pii pair<int, int> 
const int INF = 2100000000;

class BallsSeparating {
    public:
        int get_sum(int a, int b, int c, vector<int> red, vector<int> green, vector<int> blue, int sz){
            int tmp=0;
            for(int i=0; i<sz; i++){
                if(i==a || i==b||i==c)continue;
                tmp += min_p[i];
            }
            return tmp;
        }

        int minOperations(vector <int> red, vector <int> green, vector <int> blue) {

            int sz = red.size();
            if(sz<3){
                return -1;
            }

            vector< pii > sorted_d;
            for(int i=0; i<sz; i++){
                int tmp = 0;
                min_p[i] = min(min( red[i]+green[i], red[i]+blue[i]), blue[i] + green[i]);
            }

            int final_answer = INF;
            for(int i=0; i<sz; i++){
                for(int j=0; j<sz; j++){
                    for(int k=0; k<sz; k++){
                        if(i==j || j==k || i==k)continue;
                        cout<<i<<" "<<j<<" "<<k  <<endl;
                        int tmp_ans = green[i] + blue[i] + red[j] + blue[j] + red[k] + green[k]+ get_sum(i, j, k, red, green, blue, sz);
                        final_answer = min(tmp_ans, final_answer);
                    }
                }
            }
            return final_answer;




            return 0;
        }
};

// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
bool KawigiEdit_RunTest(int testNum, vector <int> p0, vector <int> p1, vector <int> p2, bool hasAnswer, int p3) {
    cout << "Test " << testNum << ": [" << "{";
    for (int i = 0; int(p0.size()) > i; ++i) {
        if (i > 0) {
            cout << ",";
        }
        cout << p0[i];
    }
    cout << "}" << "," << "{";
    for (int i = 0; int(p1.size()) > i; ++i) {
        if (i > 0) {
            cout << ",";
        }
        cout << p1[i];
    }
    cout << "}" << "," << "{";
    for (int i = 0; int(p2.size()) > i; ++i) {
        if (i > 0) {
            cout << ",";
        }
        cout << p2[i];
    }
    cout << "}";
    cout << "]" << endl;
    BallsSeparating *obj;
    int answer;
    obj = new BallsSeparating();
    clock_t startTime = clock();
    answer = obj->minOperations(p0, p1, p2);
    clock_t endTime = clock();
    delete obj;
    bool res;
    res = true;
    cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
    if (hasAnswer) {
        cout << "Desired answer:" << endl;
        cout << "\t" << p3 << endl;
    }
    cout << "Your answer:" << endl;
    cout << "\t" << answer << endl;
    if (hasAnswer) {
        res = answer == p3;
    }
    if (!res) {
        cout << "DOESN'T MATCH!!!!" << endl;
    } else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
        cout << "FAIL the timeout" << endl;
        res = false;
    } else if (hasAnswer) {
        cout << "Match :-)" << endl;
    } else {
        cout << "OK, but is it right?" << endl;
    }
    cout << "" << endl;
    return res;
}
int main() {
    bool all_right;
    all_right = true;

    vector <int> p0;
    vector <int> p1;
    vector <int> p2;
    int p3;

    {
        // ----- test 0 -----
        int t0[] = {1,1,1};
        p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
        int t1[] = {1,1,1};
        p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
        int t2[] = {1,1,1};
        p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
        p3 = 6;
        all_right = KawigiEdit_RunTest(0, p0, p1, p2, true, p3) && all_right;
        // ------------------
    }

    {
        // ----- test 1 -----
        int t0[] = {5};
        p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
        int t1[] = {6};
        p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
        int t2[] = {8};
        p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
        p3 = -1;
        all_right = KawigiEdit_RunTest(1, p0, p1, p2, true, p3) && all_right;
        // ------------------
    }

    {
        // ----- test 2 -----
        int t0[] = {4,6,5,7};
        p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
        int t1[] = {7,4,6,3};
        p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
        int t2[] = {6,5,3,8};
        p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
        p3 = 37;
        all_right = KawigiEdit_RunTest(2, p0, p1, p2, true, p3) && all_right;
        // ------------------
    }

    {
        // ----- test 3 -----
        int t0[] = {7,12,9,9,7};
        p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
        int t1[] = {7,10,8,8,9};
        p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
        int t2[] = {8,9,5,6,13};
        p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
        p3 = 77;
        all_right = KawigiEdit_RunTest(3, p0, p1, p2, true, p3) && all_right;
        // ------------------
    }

    {
        // ----- test 4 -----
        int t0[] = {842398,491273,958925,849859,771363,67803,184892,391907,256150,75799};
        p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
        int t1[] = {268944,342402,894352,228640,903885,908656,414271,292588,852057,889141};
        p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
        int t2[] = {662939,340220,600081,390298,376707,372199,435097,40266,145590,505103};
        p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
        p3 = 7230607;
        all_right = KawigiEdit_RunTest(4, p0, p1, p2, true, p3) && all_right;
        // ------------------
    }

    if (all_right) {
        cout << "You're a stud (at least on the example cases)!" << endl;
    } else {
        cout << "Some of the test cases had errors." << endl;
    }
    return 0;
}
// END KAWIGIEDIT TESTING
