#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>
#define MAX_SIZE 1<<16

using namespace std;


class RowAndCoins {
    public:
        int dp[MAX_SIZE][2];
        int b_len;
        string initial_state;
        void init(){
            memset(dp,-1,sizeof(dp));
            int state = (1<<b_len)-1;
            int j=0;
            for(int i=b_len-1; i>=0; i--){
                if(initial_state[j]=='A'){
                    dp[state^(1<<i)][0] = 1;
                    dp[state^(1<<i)][1] = 1;
                }else{
                    dp[state^(1<<i)][0] = 0;
                    dp[state^(1<<i)][1] = 0;
                }
                j++;
            }
        }
        int num_of_zero(int state){
            //cout<<"state is "<<state<<endl;
            int sum=0;
            while(state){
                if(1&state==1){
                    sum++;
                }
                state=state>>1;
            }return b_len-sum;
        }

        int test_i(int state, int i){
            return (state>>i)&1;
        }
        void set_i_1(int &state,int i){
                state = ((1<<i)|state);
        }
        void print_binary(int cur){
               if(cur==0){
                   cout<<endl;
                   return ;
               }
               else{
                   print_binary(cur>>1);
                   cout<<(cur&1);
               }
        }

        int get_state(int cur, int who){
            if(dp[cur][who]!=-1){
                return dp[cur][who];
            }

            int Alice = 0;
            for(int i=b_len-1; i>=0; i--){
                int new_state = cur;
                int state_i = test_i(new_state, i);
                int number_of_zero = num_of_zero(new_state);
                if(state_i==0){
                    int zeros_set = 0;
                    for (int j=i; j>=0&&test_i(new_state,j)==0; j--){
                        set_i_1(new_state, j);
                        zeros_set+=1;
                        if(zeros_set>=number_of_zero){
                            break;
                        }
                        int win_or_not = get_state(new_state, who^1);
                        if(win_or_not==1){
                            if(who==0){
                                Alice = 1;
                            }else{
                                Alice = 0;
                            }
                        }
                    }
                }
            }
            if(Alice==1){
                dp[cur][who] = 1;
            }else{
                dp[cur][who] = 0;
            }
            return dp[cur][who];
        }
        
        string getWinner(string cells) {
            initial_state = cells;
            b_len = cells.length();
            cout<<b_len<<endl;
            init();
            cout<<"begin "<<endl;
            int ans = get_state(0, 0);
            if(ans==1){
                return "Alice";
            }else{
                return "Bob";
            }
        }
};
/*
// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
bool KawigiEdit_RunTest(int testNum, string p0, bool hasAnswer, string p1) {
	cout << "Test " << testNum << ": [" << "\"" << p0 << "\"";
	cout << "]" << endl;
	RowAndCoins *obj;
	string answer;
	obj = new RowAndCoins();
	clock_t startTime = clock();
	answer = obj->getWinner(p0);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << "\"" << p1 << "\"" << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << "\"" << answer << "\"" << endl;
	if (hasAnswer) {
		res = answer == p1;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	string p0;
	string p1;
	
	{
	// ----- test 0 -----
	p0 = "ABBB";
	p1 = "Alice";
	all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
	// ------------------
	}
	{
	// ----- test 1 -----
	p0 = "BBBB";
	p1 = "Bob";
	all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
	// ------------------
	}
	{
	// ----- test 2 -----
	p0 = "BA";
	p1 = "Alice";
	all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
	// ------------------
	}
   // return 0;
	{
	// ----- test 3 -----
	p0 = "BABBABBB";
	p1 = "Bob";
	all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 4 -----
	p0 = "ABABBBABAABBAA";
	p1 = "Alice";
	all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 5 -----
	p0 = "BBBAAABBAAABBB";
	p1 = "Bob";
	all_right = KawigiEdit_RunTest(5, p0, true, p1) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// END KAWIGIEDIT TESTING
*/
