#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;

const int MAXN = 3000;
const double INF = 99999999;
long double dp[MAXN][MAXN];
int N;

class GraphWalkWithProbabilities {
    public:

        double get_ans(int step, int pos, vector <string> & graph, vector <int> & winprob, vector <int> & looseprob, int Start) {
            if(dp[step][pos]!=INF)return dp[step][pos];
            if(step>=MAXN){
                return 0.0;
            }

            double running_max = -INF;
            for(int i=0; i<N; i++){
                if(graph[pos][i]=='1'){
                    double con = 1-(winprob[i]+looseprob[i])/100.0;
                    double tmp = winprob[i]/100.0 + get_ans(step+1, i, graph, winprob, looseprob, Start)*con;
                    running_max = max(running_max, tmp);
                }
            }
            dp[step][pos] = running_max;
            return running_max;
        }


        double findprob(vector <string> graph, vector <int> winprob, vector <int> looseprob, int Start) {
            for(int i=0; i<MAXN; i++)for(int j=0; j<MAXN; j++){
                dp[i][j] = INF;
            }
            N = graph.size();
            return double(get_ans(0, Start, graph, winprob, looseprob, Start));
        }
};

// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
bool KawigiEdit_RunTest(int testNum, vector <string> p0, vector <int> p1, vector <int> p2, int p3, bool hasAnswer, double p4) {
    cout << "Test " << testNum << ": [" << "{";
    for (int i = 0; int(p0.size()) > i; ++i) {
        if (i > 0) {
            cout << ",";
        }
        cout << "\"" << p0[i] << "\"";
    }
    cout << "}" << "," << "{";
    for (int i = 0; int(p1.size()) > i; ++i) {
        if (i > 0) {
            cout << ",";
        }
        cout << p1[i];
    }
    cout << "}" << "," << "{";
    for (int i = 0; int(p2.size()) > i; ++i) {
        if (i > 0) {
            cout << ",";
        }
        cout << p2[i];
    }
    cout << "}" << "," << p3;
    cout << "]" << endl;
    GraphWalkWithProbabilities *obj;
    double answer;
    obj = new GraphWalkWithProbabilities();
    clock_t startTime = clock();
    answer = obj->findprob(p0, p1, p2, p3);
    clock_t endTime = clock();
    delete obj;
    bool res;
    res = true;
    cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
    if (hasAnswer) {
        cout << "Desired answer:" << endl;
        cout << "\t" << p4 << endl;
    }
    cout << "Your answer:" << endl;
    cout << "\t" << answer << endl;
    if (hasAnswer) {
        res = fabs(p4 - answer) <= 1e-9 * max(1.0, fabs(p4));
    }
    if (!res) {
        cout << "DOESN'T MATCH!!!!" << endl;
    } else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
        cout << "FAIL the timeout" << endl;
        res = false;
    } else if (hasAnswer) {
        cout << "Match :-)" << endl;
    } else {
        cout << "OK, but is it right?" << endl;
    }
    cout << "" << endl;
    return res;
}
int main() {
    bool all_right;
    all_right = true;

    vector <string> p0;
    vector <int> p1;
    vector <int> p2;
    int p3;
    double p4;
    
    {
        // ----- test 0 -----
        string t0[] = {"1"};
        p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
        int t1[] = {1};
        p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
        int t2[] = {0};
        p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
        p3 = 0;
        p4 = 1.0;
        all_right = KawigiEdit_RunTest(0, p0, p1, p2, p3, true, p4) && all_right;
        // ------------------
    }


    {
        // ----- test 1 -----
        string t0[] = {"100101000010010000100110001110", "010001000011100001000000001010", "101001000001010011001100000001", "001100101001001001001010010001", "000010000000010010100000011010", "101011100010100000100001010000", "000010101010001111111100101001", "110101010010110101000000100100", "000000101110001000000001001010", "000001111100100110000110000010", "010010000110100100010000000101", "000011100011001100101000000110", "000000000101100101010100110111", "000000001000010010111011011000", "101010001001001000001000000001", "110001000000101110011001010001", "000000111111101010010011011010", "010100000111000101001001011010", "010010110000100110100000011110", "001110000000000000011010000010", "010001101010000100001001000110", "000010100000010011101100000000", "000100000001001101000011001010", "101010110001100000001111101000", "001101100100110000001001100010", "000001101100000011111010110000", "100000101000000001000001001110", "100000111101000100010000110111", "110000001000000010001100000010", "101000101001111110100000100111"};

        p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
        int t1[] = {1, 2, 2, 2, 7, 6, 0, 3, 1, 0, 5, 2, 2, 5, 5, 4, 7, 3, 1, 2, 3, 5, 3, 2, 4, 2, 5, 4, 4, 7};
        p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
        int t2[] = {9, 36, 27, 38, 40, 12, 26, 15, 40, 50, 17, 30, 22, 35, 12, 16, 16, 24, 3, 12, 50, 48, 12, 30, 14, 16, 4, 39, 31, 13};
        p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
        p3 = 23;
        p4 = 0.5555555555555557;
        all_right = KawigiEdit_RunTest(1, p0, p1, p2, p3, true, p4) && all_right;
        // ------------------
    }

    {
        // ----- test 2 -----
        string t0[] = {"11","11"};
        p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
        int t1[] = {2,3};
        p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
        int t2[] = {3,4};
        p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
        p3 = 0;
        p4 = 0.4285714285714286;
        all_right = KawigiEdit_RunTest(2, p0, p1, p2, p3, true, p4) && all_right;
        // ------------------
    }

    {
        // ----- test 3 -----
        string t0[] = {"110","011","001"};
        p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
        int t1[] = {2,1,10};
        p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
        int t2[] = {20,20,10};
        p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
        p3 = 0;
        p4 = 0.405;
        all_right = KawigiEdit_RunTest(3, p0, p1, p2, p3, true, p4) && all_right;
        // ------------------
    }

    {
        // ----- test 4 -----
        string t0[] = {"111","111","011"};
        p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
        int t1[] = {100,1,1};
        p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
        int t2[] = {0,50,50};
        p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
        p3 = 2;
        p4 = 0.5;
        all_right = KawigiEdit_RunTest(4, p0, p1, p2, p3, true, p4) && all_right;
        // ------------------
    }

    if (all_right) {
        cout << "You're a stud (at least on the example cases)!" << endl;
    } else {
        cout << "Some of the test cases had errors." << endl;
    }
    return 0;
}
// END KAWIGIEDIT TESTING
