#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;

vector< pair<int, char> > buf;

char get_small(int maxDistance,int cur_pos){
    for(int i=0; i<buf.size(); i++){
        if(( cur_pos - buf[i].first) >= maxDistance){
            char t = buf[i].second;
            buf.erase(buf.begin()+i);
            return t;
        }
    }
    int pos = 0;
    char small = buf[0].second;
    for(int i=1; i<buf.size(); i++){
        if(small > buf[i].second){
            small = buf[i].second;
            pos = i;
        }
    }
    cout<<"pos = "<<pos<<endl;

    char t = buf[pos].second;
    buf.erase(buf.begin() + pos);
    return t;
}


class EllysScrabble {
    public:
        string getMin(string letters, int maxDistance) {
            buf.clear();
            string ans = "";
            for(int i=0; i<maxDistance; i++){
                buf.push_back(pair<int, char>(i, letters[i]));
            }

            int sz = letters.size();
            if(maxDistance>=sz){
                sort(letters.begin(), letters.end());
                return letters;
            }

            for(int i=0; i<sz; i++){
                if(i+maxDistance<sz){
                    buf.push_back(pair<int, char>(i+maxDistance, letters[i+maxDistance]));
                }
                cout<<"now in buf = "<<endl;
                for(int j=0; j<buf.size(); j++)cout<<buf[j].second<<" ";
                cout<<endl;
                char cur = get_small(maxDistance, i);
                cout<<"small est = "<<cur<<endl;
                ans += cur;
            }
            while(buf.size()>0){
                ans += get_small(maxDistance, maxDistance);
            }

            return ans;

        }
};

// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
bool KawigiEdit_RunTest(int testNum, string p0, int p1, bool hasAnswer, string p2) {
    cout << "Test " << testNum << ": [" << "\"" << p0 << "\"" << "," << p1;
    cout << "]" << endl;
    EllysScrabble *obj;
    string answer;
    obj = new EllysScrabble();
    clock_t startTime = clock();
    answer = obj->getMin(p0, p1);
    clock_t endTime = clock();
    delete obj;
    bool res;
    res = true;
    cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
    if (hasAnswer) {
        cout << "Desired answer:" << endl;
        cout << "\t" << "\"" << p2 << "\"" << endl;
    }
    cout << "Your answer:" << endl;
    cout << "\t" << "\"" << answer << "\"" << endl;
    if (hasAnswer) {
        res = answer == p2;
    }
    if (!res) {
        cout << "DOESN'T MATCH!!!!" << endl;
    } else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
        cout << "FAIL the timeout" << endl;
        res = false;
    } else if (hasAnswer) {
        cout << "Match :-)" << endl;
    } else {
        cout << "OK, but is it right?" << endl;
    }
    cout << "" << endl;
    return res;
}
int main() {
    bool all_right;
    all_right = true;

    string p0;
    int p1;
    string p2;

    {
        // ----- test 0 -----
        p0 = "TOPCODER";
        p1 = 3;
        p2 = "CODTEPOR";
        all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
        // ------------------
    }
    {
        // ----- test 1 -----
        p0 = "ESPRIT";
        p1 = 3;
        p2 = "EIPRST";
        all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
        // ------------------
    }

    {
        // ----- test 2 -----
        p0 = "BAZINGA";
        p1 = 8;
        p2 = "AABGINZ";
        all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
        // ------------------
    }

    {
        // ----- test 3 -----
        p0 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        p1 = 9;
        p2 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
        // ------------------
    }

    {
        // ----- test 4 -----
        p0 = "GOODLUCKANDHAVEFUN";
        p1 = 7;
        p2 = "CADDGAHEOOFLUKNNUV";
        all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
        // ------------------
    }

    {
        // ----- test 5 -----
        p0 = "AAAWDIUAOIWDESBEAIWODJAWDBPOAWDUISAWDOOPAWD";
        p1 = 6;
        p2 = "AAAADDEIBWAEUIODWADSBIAJWODIAWDOPOAWDUOSPWW";
        all_right = KawigiEdit_RunTest(5, p0, p1, true, p2) && all_right;
        // ------------------
    }

    {
        // ----- test 6 -----
        p0 = "ABRACADABRA";
        p1 = 2;
        p2 = "AABARACBDAR";
        all_right = KawigiEdit_RunTest(6, p0, p1, true, p2) && all_right;
        // ------------------
    }

    if (all_right) {
        cout << "You're a stud (at least on the example cases)!" << endl;
    } else {
        cout << "Some of the test cases had errors." << endl;
    }
    return 0;
}
// END KAWIGIEDIT TESTING
